adventure/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))


]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/' ,views.about, name='about'),
    path('destinations/', views.destinations_index, name='destinations_index'),
    path('destinations/<int:destination_id>/', views.destinations_detail, name='destinations_detail'),
    path('destinations/create/', views.DestinationCreate.as_view(), name='destinations_create'),
    path('destinations/<int:pk>/update/', views.DestinationUpdate.as_view(), name='destination_update'),
    path('destinations/<int:pk>/delete/', views.DestinationDelete.as_view(), name='destination_delete'),
    path('destinations/<int:destination_id>/add_restauraunts/', views.add_restauraunts, name='restauraunts'),
    path('destinations/<int:destination_id>/add_excursions/', views.add_excursions, name='excursions'),
    path('accounts/signup/', views.signup, name = 'signup')
    # path('destinations/<int:destination_id>/add_restauraunts/delete/', views.add_restaurauntsDelete.as_view(), name ='restauraunts_delete'),

]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.

class Destination(models.Model):
    location = models.CharField(max_length=100)
    budget = models.IntegerField(default=0)
    dates= models.CharField(max_length=100)
    flights = models.CharField(max_length=100)
    hotel= models.CharField(max_length=100)
    notes = models.CharField(max_length=300)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.location
    def get_absolute_url(self):
        return reverse('destinations_detail', kwargs ={'destination_id':self.id})

class Restauraunts(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} Description: {self.description}"

class Excursions(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    price =  models.IntegerField(default=0)
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.name} is {self.price}"

main_app/forms.py
from django.forms import ModelForm
from .models import Restauraunts, Excursions


class RestaurauntsForm(ModelForm):
    class Meta:
        model = Restauraunts
        fields = ('name', 'location', 'description')

class ExcursionsForm(ModelForm):
    class Meta:
        model = Excursions
        fields = ('name', 'price', 'description')

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Destination
from .forms import RestaurauntsForm, ExcursionsForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def destinations_index(request):
    destinations = Destination.objects.filter(user=request.user)
    return render(request, 'destinations/index.html', {'destinations':destinations})

@login_required
def destinations_detail(request, destination_id):
    destination = Destination.objects.get(id=destination_id)
    restauraunts_form = RestaurauntsForm()
    excursions_form = ExcursionsForm()
    return render(request, 'destinations/detail.html', {
        'destination':destination,
        'restauraunts_form':restauraunts_form,
        'excursions_form': excursions_form
         })

def add_restauraunts(request, destination_id):
    form = RestaurauntsForm(request.POST)
    if form.is_valid():
        new_restauraunts = form.save(commit=False)
        new_restauraunts.destination_id = destination_id
        new_restauraunts.save()

    return redirect('destinations_detail', destination_id=destination_id)

def add_excursions(request, destination_id):
    form = ExcursionsForm(request.POST)
    if form.is_valid():
        new_excursions = form.save(commit=False)
        new_excursions.destination_id = destination_id
        new_excursions.save()

    return redirect('destinations_detail', destination_id=destination_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('destinations_index')
        else:
            error_message = 'Not valid - try again'
    form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form, 'error': error_message})

# class add_restaurauntsDelete(DeleteView):
#     model= add_restauraunts
#     success_url = '/destinations/'
#     template_name = 'destinations/destination_confirm_delete.html'


class DestinationCreate(LoginRequiredMixin, CreateView):
    model = Destination
    fields = ('location','budget','dates', 'flights', 'hotel', 'notes')
    template_name= 'destinations/destination_form.html'
    # success_url = '/destinations/'
    def form_valid(self,form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class DestinationUpdate(LoginRequiredMixin, UpdateView):
    model = Destination
    fields = ('budget', 'flights', 'hotel', 'notes', 'dates')
    template_name= 'destinations/destination_form.html'

class DestinationDelete(LoginRequiredMixin, DeleteView):
    model= Destination
    success_url = '/destinations/'
    template_name = 'destinations/destination_confirm_delete.html'

main_app/templates/about.html
{% extends 'base.html'%}

{% block title %}
<title>About</title>

{% endblock %}

{% block content %}
    <h1>Adventure Awaits</h1>
    <h2>Adventures is a website designed for you to plan or save eveerything you worked hard in researching before your trips. You can save your favorite restauraunts, excursions and even the ones you didn't get to do. Next time you'll have it ready!</h2>
    <style>
        h1{
                   font-size: 40px;
                   text-align: center;
                   font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        }
        h2{
                font-size: 20px;
                font-weight: 300;
        }

   </style>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    {% block title%}
    <title>Adventure Awaits</title>
    {% endblock %}
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper   red lighten-3">
                <a class="left brand-logo" href="/">Adventure Awaits</a>
                <ul class="right">
                    <li>
                        <a href="/about">About</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'destinations_index'%}">Destinations</a>
                    </li>
                    <li>
                        <a href="{% url 'destinations_create'%}">Add Destination</a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                    </li><li>
                        <a href="{% url 'signup' %}">Signup</a>
                    </li>
                    {% endif %}


                </ul>
            </div>
        </nav>

    </header>
    <main class="container ">

        {% block content %}
        {% endblock %}
    </main>
    <footer class="page-footer   red lighten-3">
        <p>Copyright &copy; All Rights Reserved Cat Collector 2023</p>
    </footer>

</body>
</html>

main_app/templates/destinations/destination_confirm_delete.html
{%extends 'base.html'%}

{% block title %}
<title>Deleting {{object.name}}</title>
{% endblock %}

{% block content %}
<h1>Are you sure you want to delete {{object.name}}</h1>

<form method="POST">
    {% csrf_token%}
    <input type="submit" value="Yes, Delete {{object.name}}" class="btn red">
    <a href="{%url 'destinations_detail' object.id %}" class="btn orange">No-Cancel</a>
</form>

{% endblock %}

main_app/templates/destinations/destination_form.html
{% extends 'base.html'%}

{% block title %}
{%if object%}

<title>Update {{object.location}}</title>
{%else%}
<title>Add a Destination </title>

{% endif %}

{% endblock %}

{% block content %}
{% if object %}
<h1>Update Destination </h1>
{% else %}
<h1>Create a Destination </h1>
{% endif%}

<form method="POST">
    {% csrf_token %}
    <table>
    {{form.as_table}}
    </table>
    <input type="submit" value="Submit" class="btn blue">

</form>

{% endblock %}

main_app/templates/destinations/detail.html
{% extends 'base.html'%}

{% block title %}
<title>Destinations Detail </title>
{% endblock %}

{% block content%}
<h1>Destinations</h1>
<style>
    h1{
               font-size: 40px;
               text-align: center;
               font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
    }
</style>

<div class="row">
    <div class="col s12">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{destination.location}}</span>
                <p>Dates:  {{destination.dates}}</p>
                <p>Flight:  {{destination.flights}}</p>
                <p>Hotel: {{destination.hotel}}</p>
                <p>Notes: {{destination.notes}}</p>
            </div>

            <div class="card-action">
                <a href="{% url 'destination_update' destination.id %}">Update</a>
                <a href="{% url 'destination_delete' destination.id %}">Delete</a>
            </div>

        </div>

    </div>
    <div class="col s6">
        <form action="{% url 'restauraunts' destination.id %}" method="POST">
            {% csrf_token %}
            {{restauraunts_form.as_p }}
            <input type="submit" value="Add Restauraunt" class="btn blue">


        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Location</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                {% for restauraunts in destination.restauraunts_set.all %}
                <tr>
                    <td>{{restauraunts.name}}</td>
                    <td>{{restauraunts.location}}</td>
                    <td>{{restauraunts.description}}</td>

                </tr>
                {% endfor%}
            </tbody>
        </table>
    </div>
    <div class="col s6">
        <form action="{% url 'excursions' destination.id %}" method="POST">
            {% csrf_token %}
            {{excursions_form.as_p }}
            <input type="submit" value="Add Excursion" class="btn blue">


        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                {% for excursions in destination.excursions_set.all %}
                <tr>
                    <td>{{excursions.name}}</td>
                    <td>{{excursions.price}}</td>
                    <td>{{excursions.description}}</td>

                </tr>
                {% endfor%}
            </tbody>
        </table>
    </div>
</div>






{% endblock %}

main_app/templates/destinations/index.html
{% extends 'base.html'%}

{% block title %}
<title>All Destinations </title>
{% endblock %}

{% block content%}
<h1>All Destinations</h1>
<style>
     h1{
                font-size: 40px;
                text-align: center;
                font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
     }
</style>

{% for destination in destinations %}
<a href="/destinations/{{destination.id}}">
<div class="card">
    <div class="card-content">
        <span class="card-title">{{destination.location}}</span>
        <!-- <p>Dates:  {{destination.dates}}</p>
        <p>Flight:  {{destination.flight}}</p>
        <p>Hotel: {{destination.hotel}}</p>
        <p>Notes: {{destination.notes}}</p> -->
    </div>

</div>
</a>

{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html'%}


{% block content %}
    <h1 style="text-align:center;" ;>Welcome, Adventure Awaits! </h1>
        <h2 style="text-align:center;" >Please Log in or SignUp to Start </h2>

        <a href="{% url 'login' %}" class="btn"  style="text-align:center;">Login</a>

        <a href="{% url 'signup' %}" class="btn" style="align-items:center;" >Signup</a>
        <style>

            h2{
                font-size: 20px;
                font-weight: 300;

            }
            h1{
                font-size: 50px;
                font-style: italic;
            }
        </style>

{% endblock %}